### ISSUE TITLE
Please confirm processing speed

### ISSUE THREAD

**Issue by euquiq** [OlafenwaMoses/DeepStack_ExDark#3]
Hello @OlafenwaMoses !

First: Thank you for your work on this!! 

Now, I just replaced the standard deepstack model with yours, and the speed at which my machine is processing each frame is about half against standard deepstack model. That is: It takes almost twice the time to inspect a video frame as before.

Is this correct ?

On the other hand: it detects People (which is the only object I am interested in) with about twice the certainity, when compared against vanilla deepstack model. Nice !!

Thx again!

**Comment by OlafenwaMoses** [comment]
@euquiq thanks for the kind words. The DeepStack_ExDark mode uses the YOLOv5x model which is the most accurate but slowest custom model configuration. 

For the inbuilt detection API in DeepStack, setting your mode to HIGH will give almost identical results for detection ( for non-dark images ) .
